# Generated by Django 2.0.8 on 2018-09-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusData',
            fields=[
                ('key', models.CharField(max_length=256)),
                ('value', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
